---
- hosts: all
  sudo: True
  tasks:
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
